
import config from "./config.js";




const nextConfig = {

  env: {
    DB_URI: config.DB_URI,
    NEXTAUTH_SECRET: config.NEXTAUTH_SECRET,
    API: config.API,


    CLOUDINARY_CLOUD_NAME: config.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY: config.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: config.CLOUDINARY_API_SECRET,
    CLIENT_URL: config.CLIENT_URL,
    GOOGLE_API_KEY: config.GOOGLE_API_KEY,





    GOOGLE_CLIENT_ID :config.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET:config.GOOGLE_CLIENT_SECRET,
    GITHUB_CLIENT_ID :config.GITHUB_CLIENT_ID,

    GITHUB_CLIENT_SECRET:config.GITHUB_CLIENT_SECRET,
    FACEBOOK_CLIENT_ID :config.FACEBOOK_CLIENT_ID,
    FACEBOOK_CLIENT_SECRET:config.FACEBOOK_CLIENT_SECRET,
    LINKEDIN_CLIENT_ID :config.LINKEDIN_CLIENT_ID,
    LINKEDIN_CLIENT_SECRET:config.LINKEDIN_CLIENT_SECRET,

    RAZORPAY_KEY_SECRET:config.RAZORPAY_KEY_SECRET,
    RAZORPAY_KEY_ID:config.RAZORPAY_KEY_ID,
    PAYPAL_CLIENT_ID:config.PAYPAL_CLIENT_ID,
    PAYPAL_CLIENT_SECRET:config.PAYPAL_CLIENT_SECRET,
 
 




  },
};

export default nextConfig;
